import { LayoutHome } from "@shared/layouts";
import { RootStyleRegistry } from "@shared/providers";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function HomePageLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <RootStyleRegistry>
          <LayoutHome>{children}</LayoutHome>
        </RootStyleRegistry>
      </body>
    </html>
  );
}
